SHOW DATABASES;

CREATE DATABASE IF NOT EXISTS CLASSDB; -- IT WILL ONLY CRAETE THE DATABASE IF IT DOESNT EXIST

-- DROP DATABASE CLASSDB;

USE CLASSDB; --SELECT A DB TO WORK
SHOW TABLES;

CREATE DATABASE FBDB;

USE FBDB;

CREATE TABLE USERS (
    EMAIL VARCHAR(50) ,
    PASSWORD VARCHAR(50),
    USERNAME VARCHAR(50),
    ID INT PRIMARY KEY AUTO_INCREMENT
);

SHOW TABLES;
DESC USERS;

INSERT INTO USERS(USERNAME, EMAIL, PASSWORD) VALUES
('SANKET', 'SANKET@GMAI.COM', '123455');

INSERT INTO USERS(USERNAME, EMAIL, PASSWORD) VALUES
('SARTHAK','SJ@GMAIL.COM', '3425');

SELECT ID, EMAIL, USERNAME FROM USERS;

SELECT * FROM USERS;  --SELECT ALL THE DATA FROM TABLE

INSERT INTO USERS (USERNAME, EMAIL, PASSWORD) VALUES
('JD', 'JD@GMAIL.COM', '12444'), ('RIYA', 'RI@GMAIL.COM', '12444'), ('ROHIT', 'PR@GMAIL.COM', '12444') ; -- INSERT MULTIPLE DATA INTO THE TABLE


-- CREATE A POSTS TABLE WITH ID, CONTENT, USER_ID, CREATED_AT COLUMNS

CREATE TABLE POSTS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CONTENT VARCHAR(255),
    USER_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);
-- HERE IF WE DONT GIVE CREATED_AT VALUE THEN IT WILL GET THE VALUE OF CURRENT TIME BY DEFAULT FROM SQL SERVER 

INSERT INTO POSTS (CONTENT, USER_ID) VALUES
('HELLO WORLD', 1);  --INSERT DATA INTO THE POSTS TABLE

INSERT INTO POSTS (CONTENT, CREATED_AT, USER_ID) VALUES
('HELLOW WORLD AGAIN', '2021-01-01 2:34;50', 1); 

INSERT INTO POSTS (CONTENT, CREATED_AT, USER_ID) VALUES
('HEY THERE', '2021-01-01 2:34;54', 1);

SELECT * FROM POSTS;


SELECT * FROM USERS WHERE ID > 3;  -- SELECT WHERE ID IS GREATER THAN 3
SELECT * FROM USERS WHERE ID = 3;

SELECT * FROM POSTS WHERE USER_ID = 1 AND CONTENT = 'HELLOW WORLD AGAIN';

-- OPERATOR IN MYSQL : = , < , > , <= , >= , AND , OR , NOT, IN , BETWEEN,
-- LIKE, IS NULL , IS NOT NULL


SELECT * FROM POSTS WHERE CONTENT LIKE '%HELLO%'; -- START WITH ANYTHING END WITH ANYTHING
SELECT * FROM POSTS WHERE CONTENT LIKE '%AGAIN';

-- %AGAIN% SUBSTRING MATCH
-- %AGAIN   STARTS WITH ANYTHING BUT ENDS WITH AGAIN
-- AGAIN%   STARTS WITH AGAIN BUT CAN HAVE ANYTHING AFTER THAT


--SORT THE DATA
SELECT * FROM POSTS ORDER BY CREATED_AT; -- ASC WILL SHOW THE TABLE IN INCREASING ORDER OF THE CREATED_AT COLUMN

SELECT * FROM POSTS ORDER BY CREATED_AT DESC;

SELECT * FROM POSTS WHERE CONTENT LIKE '%WORLD' ORDER BY CREATED_AT ASC;  --STARTS WITH WORLD AND ASENDING VIA CREATED_AT COLUMN

SELECT * FROM POSTS;
DELETE FROM POSTS WHERE ID = 1; 

-- DROP TABLE POSTS;  -- DELETE THE TABLE



--UPDATE THE DATA
UPDATE POSTS SET CONTENT = 'MY WOLRD' WHERE ID = 2;  -- UPDATE THE CONTENT COLUMN TABLE WEHRE ID IS 2


