-- Pagination
-- If we want to fetch only x number of rows from the table
USE FBDB;
SELECT * FROM USERS LIMIT 2;  -- FETCH ONLY 2 ROWS

SELECT * FROM USERS LIMIT 2 OFFSET 0; -- FETCH ONLY 2 ROWS STARTING FROM 1ST RECORD 

SELECT * FROM USERS LIMIT 2 OFFSET 4; -- FETCH ONLY 2 ROWS STARTING FROM 5TH RECORD 

-- IF I WANT THE 3RD LAST RECORD
SELECT * FROM USERS LIMIT 1 OFFSET 2;  --START FROM 3RD ROW AND GO TO ONLY ONE ROW

