USE FBDB;

SELECT * FROM COMMENTS; 
SELECT * FROM POSTS;

-- ** INNER JOIN **

--THIS BELOW LINE WILL JOIN USERS TABLE TO COMMENTS TABLE WHERE ID IN USERS COLUMN MACHES THE USER_ID IN COMMENTS TABLE
SELECT * FROM COMMENTS JOIN USERS ON COMMENTS.USER_ID = USERS.ID; 

-- THIS LINE WILL COMBINE THE RESULT OF ABOVE LINE WITH THE POST TABLE CONTENT WHERE ID COLUMN VALUE IN THE POST TABLE MATCHES WITH POST_ID COLUMN IN THE COMMENTS TABLE
SELECT * FROM COMMENTS JOIN USERS ON COMMENTS.USER_ID = USERS.ID JOIN POSTS ON COMMENTS.POST_ID = POSTS.ID;


-- ** RIGHT JOIN **
-- JOIN THE COMMON DATA AND ALL THE DATA PRESENT IN THE RIGHT TABLE

SELECT * FROM COMMENTS RIGHT JOIN POSTS ON COMMENTS.POST_ID = POSTS.ID;
-- HERE CONTENT IN THE COMMENTS TABLE IS MISSING FOR 3 RD AND 4 TH POST ID BECUASE FOR 3RD AND 4TH POSTS THERE ARE NO COMMENTS.

